# <a href='https://towardsdatascience.com/an-overview-of-resnet-and-its-variants-5281e2f56035'>ResNet</a>


## Load Images

In [1]:
from data import Images_load

In [2]:
train, validation, test = Images_load.load_data()

Data has apparently already been downloaded and unpacked.


  2%|▏         | 62/4006 [00:00<00:06, 611.82it/s]

Data has apparently already been downloaded and unpacked.


100%|██████████| 4192/4192 [00:07<00:00, 575.22it/s]


In [3]:
from models.Image_classifier import Resnet50

Using TensorFlow backend.


### Experiment 1

In [7]:
%%time 
CM, CR = Resnet50.run_resnet50(train, validation, test)

Train on 4611 samples, validate on 1538 samples
Epoch 1/10
 - 1510s - loss: 1.3411 - accuracy: 0.6141 - val_loss: 0.7431 - val_accuracy: 0.5169

Epoch 00001: val_accuracy improved from -inf to 0.51691, saving model to ResNet50.01-0.74.h5

Epoch 2/10
 - 1444s - loss: 0.8681 - accuracy: 0.6506 - val_loss: 7.0479 - val_accuracy: 0.5953

Epoch 00002: val_accuracy improved from 0.51691 to 0.59525, saving model to ResNet50.02-7.05.h5
Epoch 3/10
 - 1454s - loss: 0.8189 - accuracy: 0.6302 - val_loss: 0.6574 - val_accuracy: 0.5927

Epoch 00003: val_accuracy did not improve from 0.59525
Epoch 4/10
 - 1447s - loss: 0.7420 - accuracy: 0.6728 - val_loss: 1.0174 - val_accuracy: 0.6141

Epoch 00004: val_accuracy improved from 0.59525 to 0.61411, saving model to ResNet50.04-1.02.h5
Epoch 5/10
 - 1447s - loss: 0.6664 - accuracy: 0.6914 - val_loss: 0.6506 - val_accuracy: 0.6336

Epoch 00005: val_accuracy improved from 0.61411 to 0.63362, saving model to ResNet50.05-0.65.h5
Epoch 6/10
 - 1441s - loss: 0.

In [8]:
print('Confusion Matrix')
print(CM)
print('Classification Report')
print(CR)

Confusion Matrix
[[635 366]
 [268 781]]
Classification Report
               precision    recall  f1-score   support

    Depressed       0.70      0.63      0.67      1001
Not depressed       0.68      0.74      0.71      1049

     accuracy                           0.69      2050
    macro avg       0.69      0.69      0.69      2050
 weighted avg       0.69      0.69      0.69      2050



### Experiment 2

In [4]:
%%time 
CM, CR = Resnet50.run_resnet50(train, validation, test, lr= .0001)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 4611 samples, validate on 1538 samples


Epoch 1/10
 - 1558s - loss: 0.8704 - accuracy: 0.5835 - val_loss: 0.7313 - val_accuracy: 0.4844

Epoch 00001: val_accuracy improved from -inf to 0.48440, saving model to ResNet50.01-0.73.h5

Epoch 2/10
 - 1432s - loss: 0.6630 - accuracy: 0.6712 - val_loss: 0.7963 - val_accuracy: 0.4844

Epoch 00002: val_accuracy did not improve from 0.48440
Epoch 3/10
 - 1447s - loss: 0.5620 - accuracy: 0.7259 - val_loss: 0.7604 - val_accuracy: 0.4844
Restoring model weights from the end of the best epoch

Epoch 00003: val_accuracy did not improve from 0.48440
Epoch 00003: early stopping
Train accuracy: 0.4903491735458374
Test accuracy: 0.4882926940917969


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


CPU times: user 8h 27min 54s, sys: 3h 25min 38s, total: 11h 53min 32s
Wall time: 1h 31min 12s


In [5]:
print('Confusion Matrix')
print(CM)
print('Classification Report')
print(CR)

Confusion Matrix
[[1001    0]
 [1049    0]]
Classification Report
               precision    recall  f1-score   support

    Depressed       0.49      1.00      0.66      1001
Not depressed       0.00      0.00      0.00      1049

     accuracy                           0.49      2050
    macro avg       0.24      0.50      0.33      2050
 weighted avg       0.24      0.49      0.32      2050



### Experiment 3


In [4]:
%%time 
CM, CR = Resnet50.run_resnet50(train, validation, test, epochs=10)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.



Train on 4611 samples, validate on 1538 samples


Epoch 1/10
 - 1492s - loss: 2.4897 - accuracy: 0.6127 - val_loss: 0.6721 - val_accuracy: 0.6144

Epoch 00001: val_accuracy improved from -inf to 0.61443, saving model to ResNet50.01-0.67.h5

Epoch 2/10
 - 1435s - loss: 1.2611 - accuracy: 0.6348 - val_loss: 0.7472 - val_accuracy: 0.5247

Epoch 00002: val_accuracy did not improve from 0.61443
Epoch 3/10
 - 1451s - loss: 0.7192 - accuracy: 0.6860 - val_loss: 0.6530 - val_accuracy: 0.6203

Epoch 00003: val_accuracy improved from 0.61443 to 0.62029, saving model to ResNet50.03-0.65.h5
Epoch 4/10
 - 1436s - loss: 0.7756 - accuracy: 0.6886 - val_loss: 0.8505 - val_accuracy: 0.5410

Epoch 00004: val_accuracy did not improve from 0.62029
Epoch 5/10
 - 1447s - loss: 0.8227 - accuracy: 0.6667 - val_loss: 0.8399 - val_accuracy: 0.5156
Restoring model weights from the end of the best epoch

Epoch 00005: val_accuracy 

In [5]:
print('Confusion Matrix')
print(CM)
print('Classification Report')
print(CR)

Confusion Matrix
[[268 733]
 [ 96 953]]
Classification Report
               precision    recall  f1-score   support

    Depressed       0.74      0.27      0.39      1001
Not depressed       0.57      0.91      0.70      1049

     accuracy                           0.60      2050
    macro avg       0.65      0.59      0.54      2050
 weighted avg       0.65      0.60      0.55      2050



### Experiment 4

In [7]:
%%time 
CM, CR = Resnet50.run_resnet50(train, validation, test, batch_size=50)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.



Train on 4611 samples, validate on 1538 samples


Epoch 1/10
 - 1500s - loss: 1.8641 - accuracy: 0.5834 - val_loss: 0.6544 - val_accuracy: 0.6190

Epoch 00001: val_accuracy improved from -inf to 0.61899, saving model to ResNet50.01-0.65.h5

Epoch 2/10
 - 1452s - loss: 0.7156 - accuracy: 0.6738 - val_loss: 0.7534 - val_accuracy: 0.5039

Epoch 00002: val_accuracy did not improve from 0.61899
Epoch 3/10
 - 1459s - loss: 0.6721 - accuracy: 0.6747 - val_loss: 0.6098 - val_accuracy: 0.6795

Epoch 00003: val_accuracy improved from 0.61899 to 0.67945, saving model to ResNet50.03-0.61.h5
Epoch 4/10
 - 1459s - loss: 0.6265 - accuracy: 0.6881 - val_loss: 0.6037 - val_accuracy: 0.6977

Epoch 00004: val_accuracy improved from 0.67945 to 0.69766, saving model to ResNet50.04-0.60.h5
Epoch 5/10
 - 1493s - loss: 0.6050 - accuracy: 0.6996 - val_loss: 0.5807 - val_accuracy: 0.7230

Epoch 00005: val_accuracy improved from 

In [8]:
print('Confusion Matrix')
print(CM)
print('Classification Report')
print(CR)

Confusion Matrix
[[787 214]
 [370 679]]
Classification Report
               precision    recall  f1-score   support

    Depressed       0.68      0.79      0.73      1001
Not depressed       0.76      0.65      0.70      1049

     accuracy                           0.72      2050
    macro avg       0.72      0.72      0.71      2050
 weighted avg       0.72      0.72      0.71      2050



### Experiment 5


In [4]:
%%time 
CM, CR = Resnet50.run_resnet50(train, validation, test, batch_size=50,epochs=30)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.



Train on 4611 samples, validate on 1538 samples


Epoch 1/30
 - 1492s - loss: 2.3615 - accuracy: 0.5797 - val_loss: 0.8068 - val_accuracy: 0.4844

Epoch 00001: val_accuracy improved from -inf to 0.48440, saving model to ResNet50.01-0.81.h5

Epoch 2/30
 - 1458s - loss: 0.9057 - accuracy: 0.6196 - val_loss: 1.1554 - val_accuracy: 0.4844

Epoch 00002: val_accuracy did not improve from 0.48440
Epoch 3/30
 - 1460s - loss: 0.6772 - accuracy: 0.6582 - val_loss: 0.7958 - val_accuracy: 0.5111

Epoch 00003: val_accuracy improved from 0.48440 to 0.51105, saving model to ResNet50.03-0.80.h5
Epoch 4/30
 - 1454s - loss: 0.6158 - accuracy: 0.6890 - val_loss: 0.6010 - val_accuracy: 0.6899

Epoch 00004: val_accuracy improved from 0.51105 to 0.68986, saving model to ResNet50.04-0.60.h5
Epoch 5/30
 - 1463s - loss: 0.5771 - accuracy: 0.7072 - val_loss: 0.5911 - val_accuracy: 0.6866

Epoch 00005: val_accuracy did not improv

In [5]:
print('Confusion Matrix')
print(CM)
print('Classification Report')
print(CR)

Confusion Matrix
[[719 282]
 [318 731]]
Classification Report
               precision    recall  f1-score   support

    Depressed       0.69      0.72      0.71      1001
Not depressed       0.72      0.70      0.71      1049

     accuracy                           0.71      2050
    macro avg       0.71      0.71      0.71      2050
 weighted avg       0.71      0.71      0.71      2050



### Experiment 6

In [6]:
%%time 
CM, CR = Resnet50.run_resnet50(train, validation, test, batch_size=32,epochs=30)

Train on 4611 samples, validate on 1538 samples
Epoch 1/30
 - 1434s - loss: 1.4976 - accuracy: 0.5975 - val_loss: 1.2120 - val_accuracy: 0.4837

Epoch 00001: val_accuracy improved from -inf to 0.48375, saving model to ResNet50.01-1.21.h5
Epoch 2/30
 - 1411s - loss: 0.8718 - accuracy: 0.6337 - val_loss: 0.6475 - val_accuracy: 0.6430

Epoch 00002: val_accuracy improved from 0.48375 to 0.64304, saving model to ResNet50.02-0.65.h5
Epoch 3/30
 - 1416s - loss: 0.6556 - accuracy: 0.6667 - val_loss: 0.6151 - val_accuracy: 0.6756

Epoch 00003: val_accuracy improved from 0.64304 to 0.67555, saving model to ResNet50.03-0.62.h5
Epoch 4/30
 - 1409s - loss: 0.6061 - accuracy: 0.6881 - val_loss: 0.5873 - val_accuracy: 0.6983

Epoch 00004: val_accuracy improved from 0.67555 to 0.69831, saving model to ResNet50.04-0.59.h5
Epoch 5/30
 - 1420s - loss: 0.6063 - accuracy: 0.6918 - val_loss: 0.5870 - val_accuracy: 0.6964

Epoch 00005: val_accuracy did not improve from 0.69831
Epoch 6/30
 - 1427s - loss: 0.5

In [ ]:
print('Confusion Matrix')
print(CM)
print('Classification Report')
print(CR)

Confusion Matrix
[[596 405]
 [219 830]]
Classification Report
               precision    recall  f1-score   support

    Depressed       0.73      0.60      0.66      1001
Not depressed       0.67      0.79      0.73      1049

     accuracy                           0.70      2050
    macro avg       0.70      0.69      0.69      2050
 weighted avg       0.70      0.70      0.69      2050



### Experiment 7

In [6]:
%%time 
CM, CR = Resnet50.run_resnet50(train, validation, test, batch_size=50,epochs=30,lr=.0003)

Train on 4611 samples, validate on 1538 samples
Epoch 1/30
 - 1569s - loss: 1.7274 - accuracy: 0.5988 - val_loss: 0.6953 - val_accuracy: 0.4844

Epoch 00001: val_accuracy improved from -inf to 0.48440, saving model to ResNet50.01-0.70.h5
Epoch 2/30
 - 1557s - loss: 1.0233 - accuracy: 0.6664 - val_loss: 0.6545 - val_accuracy: 0.6346

Epoch 00002: val_accuracy improved from 0.48440 to 0.63459, saving model to ResNet50.02-0.65.h5
Epoch 3/30
 - 1532s - loss: 0.9601 - accuracy: 0.6821 - val_loss: 0.6460 - val_accuracy: 0.6242

Epoch 00003: val_accuracy did not improve from 0.63459
Epoch 4/30
 - 1535s - loss: 0.8202 - accuracy: 0.6701 - val_loss: 4.0647 - val_accuracy: 0.5052

Epoch 00004: val_accuracy did not improve from 0.63459
Epoch 5/30
 - 1534s - loss: 0.6978 - accuracy: 0.6992 - val_loss: 4.6297 - val_accuracy: 0.6385
Restoring model weights from the end of the best epoch

Epoch 00005: val_accuracy improved from 0.63459 to 0.63849, saving model to ResNet50.05-4.63.h5
Epoch 00005: earl

In [7]:
print('Confusion Matrix')
print(CM)
print('Classification Report')
print(CR)

Confusion Matrix
[[772 229]
 [497 552]]
Classification Report
               precision    recall  f1-score   support

    Depressed       0.61      0.77      0.68      1001
Not depressed       0.71      0.53      0.60      1049

     accuracy                           0.65      2050
    macro avg       0.66      0.65      0.64      2050
 weighted avg       0.66      0.65      0.64      2050

