# Test best Models:
## BiLSTM+ GloVe:
    10k not preprocessed Tweet:

In [1]:
import pandas as pd
test_data = pd.read_csv("data/test_data.csv")


In [2]:
classes_index = {
    1 : "Depressed",
    0 : "Not depressed"
}
from tensorflow import keras
import pickle
model = keras.models.load_model('Exp_10k_32ep/model_BiGloVe.h5')
# loading
with open('Exp_10k_32ep/tokenizer_BiGlove.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
def predict_tweet_BiGlove(text_to_predict):
    test_sequence = tokenizer.texts_to_sequences([text_to_predict])
    test_data = pad_sequences(test_sequence, maxlen=99)
    predictions = model.predict(test_data)
    prediction = np.argmax(predictions)
    print("The person who tweeted this is {}\n".format(classes_index[prediction]))
    ranking = predictions.argsort()[-2:][::-1]
    for i in reversed(range(0, 2)):
        rank = ranking[0][i]
        print("{:>10} : {:.5f}%".format(classes_index[rank], predictions[0][rank]*100))

In [4]:
for i in range(0,40):
    print(test_data["Tweet"][i])
    print()
    predict_tweet_BiGlove(test_data["Tweet"][i])
    print("*************************************************************************************")

Psikologi:( smoga bs kesampaian

The person who tweeted this is Depressed

 Depressed : 63.46477%
Not depressed : 36.53523%
*************************************************************************************
Stare at the sun

The person who tweeted this is Depressed

 Depressed : 73.99948%
Not depressed : 26.00052%
*************************************************************************************
Please stay Safe Cathy! Always enjoying your art work. Cheers 🍻

The person who tweeted this is Depressed

 Depressed : 82.09192%
Not depressed : 17.90809%
*************************************************************************************
Tough life!  Waiting to work on such a beautiful day 🌈🌞 #danceteacherlife #ballet #vancouver  https://www.instagram.com/p/BxlSxn5Fnjk/?igshid=ygym9vzdijme …

The person who tweeted this is Not depressed

Not depressed : 96.98225%
 Depressed : 3.01775%
*************************************************************************************
Hahahaha

The p

In [5]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np 
from tqdm import trange
from tensorflow.keras.utils import to_categorical
def evaluate_test(data):
    d=data["Tweet"].tolist()  
    sequences = tokenizer.texts_to_sequences(d)
    seqs = pad_sequences(sequences, maxlen=99)
    y = to_categorical(data["label"].tolist())
    score = model.evaluate(seqs,y, verbose=2)
    print('Test accuracy:', score[ 1 ])
    Y_pred = model.predict(seqs)
    y_pred = np.argmax(Y_pred, axis=1)
    y_classes = np.argmax(y, axis=1)
    target_names = [ 'Depressed', 'Not depressed' ]
    print(confusion_matrix(y_classes, y_pred) )
    print(classification_report(y_classes, y_pred, target_names=target_names))

In [6]:
%%time
evaluate_test(test_data)

9998/1 - 105s - loss: 0.5350 - acc: 0.6390
Test accuracy: 0.63902783
[[1701 3298]
 [ 311 4688]]
               precision    recall  f1-score   support

    Depressed       0.85      0.34      0.49      4999
Not depressed       0.59      0.94      0.72      4999

     accuracy                           0.64      9998
    macro avg       0.72      0.64      0.60      9998
 weighted avg       0.72      0.64      0.60      9998

CPU times: user 7min 34s, sys: 4min 59s, total: 12min 33s
Wall time: 3min 28s


## Preprocessed 10k Tweet 32 batch size:

In [7]:
import pandas as pd
data = pd.read_csv("Exp_prep_10k_32ep/test_data.csv")


In [8]:
classes_index = {
    1 : "Depressed",
    0 : "Not depressed"
}
from tensorflow import keras
import pickle
model = keras.models.load_model('Exp_prep_10k_32ep/model_BiGloVe.h5')
# loading
with open('Exp_prep_10k_32ep/tokenizer_BiGlove.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
def predict_tweet_BiGlove(text_to_predict):
    test_sequence = tokenizer.texts_to_sequences([text_to_predict])
    test_data = pad_sequences(test_sequence, maxlen=197)
    predictions = model.predict(test_data)
    prediction = np.argmax(predictions)
    print("The person who tweeted this is {}\n".format(classes_index[prediction]))
    ranking = predictions.argsort()[-2:][::-1]
    for i in reversed(range(0, 2)):
        rank = ranking[0][i]
        print("{:>10} : {:.5f}%".format(classes_index[rank], predictions[0][rank]*100))

In [29]:
for i in range(0,20):
    print(data["Tweet"][i])
    print()
    
    predict_tweet_BiGlove(data["Tweet"][i])
    print("*************************************************************************************")

 fa single mate lot ya team become double

The person who tweeted this is Depressed

 Depressed : 71.43446%
Not depressed : 28.56554%
*************************************************************************************
 wish simple sesi

The person who tweeted this is Depressed

 Depressed : 70.92521%
Not depressed : 29.07479%
*************************************************************************************
 east coast trick heart_suit snowman_without_snow snowman_without_snow snowman_without_snow cloud_with_snow cloud_with_snow cloud_with_snow cloud_with_snow heart_suit heart_suit heart_suit snowflake snowflake snowflake pic xhbzvudoa8

The person who tweeted this is Not depressed

Not depressed : 61.38417%
 Depressed : 38.61583%
*************************************************************************************
 crying_face holy crap broken_heart

The person who tweeted this is Depressed

 Depressed : 73.93242%
Not depressed : 26.06758%
****************************************

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np 
from tqdm import trange
from tensorflow.keras.utils import to_categorical
def evaluate_test(data):
    d=data["Tweet"].astype(str).tolist()    
    sequences = tokenizer.texts_to_sequences(d)
    seqs = pad_sequences(sequences, maxlen=197)
    y = to_categorical(data["label"].tolist())
    score = model.evaluate(seqs,y, verbose=2)
    print('Test accuracy:', score[ 1 ])
    Y_pred = model.predict(seqs)
    y_pred = np.argmax(Y_pred, axis=1)
    y_classes = np.argmax(y, axis=1)
    target_names = [ 'Depressed', 'Not depressed' ]
    print(confusion_matrix(y_classes, y_pred) )
    print(classification_report(y_classes, y_pred, target_names=target_names))

In [16]:
%%time
evaluate_test(data)

1374/1 - 24s - loss: 0.5501 - acc: 0.6958
Test accuracy: 0.6957787
[[386 249]
 [169 570]]
               precision    recall  f1-score   support

    Depressed       0.70      0.61      0.65       635
Not depressed       0.70      0.77      0.73       739

     accuracy                           0.70      1374
    macro avg       0.70      0.69      0.69      1374
 weighted avg       0.70      0.70      0.69      1374

CPU times: user 1min 55s, sys: 55.6 s, total: 2min 51s
Wall time: 45.2 s


## Preprocessed 10k Tweet 128 batch size:

In [30]:
import pandas as pd
data = pd.read_csv("Exp_prep_10k_128ep/test_data.csv")


In [31]:
classes_index = {
    1 : "Depressed",
    0 : "Not depressed"
}
from tensorflow import keras
import pickle
model = keras.models.load_model('Exp_prep_10k_128ep/model_BiGloVe.h5')
# loading
with open('Exp_prep_10k_128ep/tokenizer_BiGlove.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

In [32]:
for i in range(0,20):
    print(data["Tweet"][i])
    print()
    
    predict_tweet_BiGlove(data["Tweet"][i])
    print("*************************************************************************************")

 jar downplay weeks set business bro make test distribution try get full control make zillions maybe trump mad at allow news leak media people url …

The person who tweeted this is Depressed

 Depressed : 74.23122%
Not depressed : 25.76878%
*************************************************************************************
 get tell percent work force at work not go back work week love house tell every house get unite “ no elongate ” love at home take take apart kitchen cabinets kid break no love at home

The person who tweeted this is Depressed

 Depressed : 84.68218%
Not depressed : 15.31782%
*************************************************************************************
 mhm mean closest friend not realize 

The person who tweeted this is Depressed

 Depressed : 78.11868%
Not depressed : 21.88132%
*************************************************************************************
 momlife nannylife sahmlife nanny nannying stayathomemom homeschool homeschooling homeschoolli

In [33]:
%%time
evaluate_test(data)

1374/1 - 25s - loss: 0.5323 - acc: 0.7220
Test accuracy: 0.7219796
[[322 273]
 [109 670]]
               precision    recall  f1-score   support

    Depressed       0.75      0.54      0.63       595
Not depressed       0.71      0.86      0.78       779

     accuracy                           0.72      1374
    macro avg       0.73      0.70      0.70      1374
 weighted avg       0.73      0.72      0.71      1374

CPU times: user 1min 58s, sys: 57.9 s, total: 2min 56s
Wall time: 47 s
